package com.spire.base.service;

public class Constants {
	public static final String candidate_Id = "6030:6005:a85ee5e026be4046b9a7116e580fd639";
	public static final String candidate_Id1 = "6079:6005:c3dbcb92dd8e4fd29af671d09d79b4fd";
	public static final String requisition_Id = "6030:6066:ef7a79270ffd40ae93adc4cfc5b9da7b";
	public static final String requisition_Id1 = "6079:6066:055c8bc96fe34ef6b3c036b2136d4d20";
	public static final String candidate_Id2 = "6079:6005:c3dbcb92dd8e4fd29af671d09d79b4fd";
	public static final String user_Id = "user@uat.com";
	public static final String password = "spire@123";
	public static final String partial_Skill_to_search="Ja";
    public static final String full_skill_to_search="Java%20Script";
    public static final String partial_institute_to_search="UNIVERSITY";
    public static final String full_institute_to_search="BANGALORE%20UNIVERSITY";
    public static final String partial_education_to_search="Diploma";
    public static final String full_education_to_search="Diploma%20in%20Computer%20Applications";
    public static final String full_employer_to_search="Wipro%20TECHNOLOGIES";
    public static final String partial_employer_to_search="WIPRO";
    public static final String full_location_to_search="Bangalore";
    public static final String partial_location_to_search="ba";
    public static final String full_sourcetype_to_search="Referral%20-%20Employee";
    public static final String partial_sourcetype_to_search="Referral";
    public static final String full_sourcename_to_search="Naukri";
    public static final String partial_sourcename_to_search="N";
    public static final String full_status_to_search="open";
    public static final String partial_status_to_search="Black";
    public static final String skill="skill";
    public static final String institute="institutename";
    public static final String education="education";
    public static final String employer="employername";
    public static final String location="locationname";
    public static final String sourcetype="sourcetype";
    public static final String sourcename="sourcename";
    public static final String status="status";
    public static final String candidate_resume="6079:6005:09c8cccc8ea74ad7a890475063bec46e";
    public static final String changeStats="6079:6066:28ec518324ed4d8b9562b2b6ffb72804";
    public static final String test_status ="Test";
    public static final String test_status1 = "Test1";
    public static final String candidate_deallocate = "6079:6005:25ae5f1585aa4f409080c4a09eabc26b";
	public static final String requisition_deallocate = "6079:6066:5bcc7bd0f80a4011bc5314e580804ec1";		
}
