package com.spire.base.service;

public class Constants {
	public static final String candidate_Id = "6100:6005:9b1106829ee94d91b38f8e14e1aa3ca0";
	public static final String candidate_Id1 = "6100:6005:bb17361fac2a46978169b746b3cafe9e";
	public static final String requisition_Id = "6100:6066:846ba741d5184547b136eaa2af13835a";
	public static final String requisition_Id1 = "6100:6066:ed8d850ce3c044bba5fd90c25fcd00ad";
	public static final String candidate_Id2 = "6079:6005:c3dbcb92dd8e4fd29af671d09d79b4fd";
	public static final String user_Id = "sekhar@accenturebpodev.com";
	public static final String password = "iVkzceza";
	public static final String partial_Skill_to_search="Ja";
    public static final String full_skill_to_search="Java%20Script";
    public static final String partial_institute_to_search="UNIVERSITY";
    public static final String full_institute_to_search="BANGALORE%20UNIVERSITY";
    public static final String partial_education_to_search="Diploma";
    public static final String full_education_to_search="Diploma%20in%20Computer%20Applications";
    public static final String full_employer_to_search="Wipro%20TECHNOLOGIES";
    public static final String partial_employer_to_search="WIPRO";
    public static final String full_location_to_search="Bangalore";
    public static final String partial_location_to_search="ba";
    public static final String full_sourcetype_to_search="Referral%20-%20Employee";
    public static final String partial_sourcetype_to_search="Referral";
    public static final String full_sourcename_to_search="Naukri";
    public static final String partial_sourcename_to_search="N";
    public static final String full_status_to_search="open";
    public static final String partial_status_to_search="Black";
    public static final String skill="skill";
    public static final String institute="institutename";
    public static final String education="education";
    public static final String employer="employername";
    public static final String location="locationname";
    public static final String sourcetype="sourcetype";
    public static final String sourcename="sourcename";
    public static final String status="status";
    public static final String candidate_resume="6079:6005:09c8cccc8ea74ad7a890475063bec46e";
    public static final String changeStats="6100:6005:9b1106829ee94d91b38f8e14e1aa3ca0";
    public static final String test_status ="Test";
    public static final String test_status1 = "Test1";
    public static final String candidate_deallocate = "6079:6005:25ae5f1585aa4f409080c4a09eabc26b";
	public static final String requisition_deallocate = "6079:6066:5bcc7bd0f80a4011bc5314e580804ec1";		
}
